Revert "test: releasetools: add devices to override AssertDevice"
This reverts commit bef1f691e1b021edf317dc145dffc8e865577a13.

Buld crash with
Traceback (most recent call last):
  File "./build/tools/releasetools/ota_from_target_files", line 1636, in <module>
    main(sys.argv[1:])
  File "./build/tools/releasetools/ota_from_target_files", line 1537, in main
    extra_option_handler=option_handler)
  File "/home/b--b/CM-Sources/android/AOSP-5.1/build/tools/releasetools/common.py", line 660, in ParseOptions
    if extra_option_handler is None or not extra_option_handler(o, a):
  File "./build/tools/releasetools/ota_from_target_files", line 1511, in option_handler
    OPTIONS.override_device = jflte, jfltexx, i9505, GT-I9505, jgedlte, i9505g, GT-I9505G, jfltevzw, jfltespr, jflterefreshspr, jfltetmo, jfltecri, jfltecsp, jflteatt, jfltecan, jflteusc, jfltezm
NameError: global name 'jflte' is not defined